const API_URL = "https://script.google.com/macros/s/AKfycbzoTls_spQlTGr2D7glpSbkHSJ91nOtskUAo2nDaZH_kdKwEN7soqE7lBVLMVgnptH3/exec";

// Q01-Q03: Pay & Allowance | Q04-Q06: Bonus | Q07-Q09: Profit Sharing
// Q10-Q12: Commission | Q13-Q15: Performance-Linked Incentives
// Q16-Q19: Stock Options | Q20: six-method comparison.
const SEVEN_POINT=["Strongly decreases","Decreases","Slightly decreases","No effect","Slightly increases","Increases","Strongly increases"];
const QUESTIONS=[
 {id:1,title:"Which pay or allowance components does your organisation provide to employees?",type:"multi",note:"Select all that apply. Choose “Other” only when the benefit is not listed.",options:["Basic pay / salary","Dearness / cost-of-living allowance","Housing / rent allowance","Travel / conveyance allowance","Medical / health allowance","Meal / food allowance","Overtime allowance","Other financial allowance / benefit"],other:true},
 {id:2,title:"How satisfied are you with the pay and allowances you receive for the work you do?",type:"range",min:0,max:100,step:1,defaultValue:50,minLabel:"0% — Not satisfied",maxLabel:"100% — Completely satisfied"},
 {id:3,title:"When additional pay or an allowance is available for extra duties or overtime, how does it affect your willingness to take that work?",type:"metric7",options:SEVEN_POINT},
 {id:4,title:"How is a bonus generally provided in your organisation?",type:"single",options:["Fixed / annual bonus","Performance-based bonus","Target / project completion bonus","Festival / occasion bonus","More than one of the above","No bonus provided","I do not know"]},
 {id:5,title:"How clearly are the conditions for receiving a bonus explained to employees?",type:"single",options:["Very clear","Clear","Partly clear","Unclear","Not clear at all","I do not know"]},
 {id:6,title:"To what extent does the possibility of receiving a bonus affect your motivation to improve your performance?",type:"metric7",options:SEVEN_POINT},
 {id:7,title:"Does your organisation share part of its profit with employees through a financial reward?",type:"single",options:["Yes, regularly","Yes, sometimes","No","I do not know"]},
 {id:8,title:"When employees receive a share of organisational profit, what effect does it have on motivation?",type:"single",options:["No effect","Small positive effect","Moderate positive effect","Strong positive effect","Very strong positive effect"]},
 {id:9,title:"How fair and transparent do you find the way profit-based rewards are determined and distributed?",type:"single",options:["Very fair and transparent","Fair and reasonably transparent","Neither fair nor unfair / mixed","Unfair or not transparent","Very unfair / not transparent","I do not know"]},
 {id:10,title:"How are commission-based incentives used in your organisation?",type:"single",options:["They are part of my own role's earnings","They are used for sales / target-based roles","They are offered only to some roles or departments","They are not used","I do not know"]},
 {id:11,title:"Where commission is used, how clearly are commission rates and payment conditions explained?",type:"single",options:["Very clear","Clear","Partly clear","Unclear","Not clear at all","Not applicable / commission is not used","I do not know"]},
 {id:12,title:"Considering your experience or understanding of commission-based earning, what effect does it have on motivation to achieve measurable targets?",type:"metric7",options:SEVEN_POINT},
 {id:13,title:"How strongly are financial incentives linked to measurable individual or team performance in your organisation?",type:"single",options:["Not linked at all","Slightly linked","Moderately linked","Strongly linked","Very strongly linked","I do not know"]},
 {id:14,title:"When financial rewards are directly linked to your performance or targets, what effect do they have on your effort?",type:"metric7",options:SEVEN_POINT},
 {id:15,title:"Which performance-linked arrangement would motivate you most for extra effort?",type:"single",options:["Fixed pay without performance variation","Fixed pay + periodic performance bonus","Target-based incentive / commission","Team performance incentive","A combination of performance-linked methods"]},
 {id:16,title:"Before this survey, how familiar were you with stock options or shares being used as a financial motivation method?",type:"single",options:["I knew this was a financial motivation method","I had heard of it but was not familiar with the idea","I was not aware of it"]},
 {id:17,title:"Does your organisation offer employees stock options or shares as part of compensation or rewards?",type:"single",options:["Yes, to me / my role","Yes, to some employees or roles","No","I do not know"]},
 {id:18,title:"If stock options were offered with clear conditions, how would they affect your long-term motivation to contribute to organisational success?",type:"metric7",options:SEVEN_POINT},
 {id:19,title:"For a reward of similar present value, which would you prefer?",type:"single",options:["Cash reward now","Stock options / shares with long-term value","A split between cash and stock options","It would depend on the conditions"]},
 {id:20,title:"Which one of the six financial motivation methods has the greatest motivating effect on you?",type:"single",options:["Pay and Allowance","Bonus","Profit Sharing","Commission","Performance-Linked Incentives","Stock Options","None of these has a major effect","I cannot judge"]}
];

const landingView=document.getElementById("landingView"),surveyView=document.getElementById("surveyView"),thankView=document.getElementById("thankView"),startSurveyBtn=document.getElementById("startSurveyBtn"),surveyForm=document.getElementById("surveyForm"),questionsContainer=document.getElementById("questionsContainer"),progressCount=document.getElementById("progressCount"),progressFill=document.getElementById("progressFill"),submitBtn=document.getElementById("submitBtn"),submitStatus=document.getElementById("submitStatus"),workplacePhoto=document.getElementById("workplacePhoto"),captchaQuestion=document.getElementById("captchaQuestion"),captchaAnswer=document.getElementById("captchaAnswer"),newCaptchaBtn=document.getElementById("newCaptchaBtn"),agreeTerms=document.getElementById("agreeTerms");
let captcha={a:0,b:0};
const overlay=document.createElement("div");overlay.className="loading-overlay";overlay.innerHTML='<div class="spinner" aria-label="Submitting"></div>';document.body.appendChild(overlay);

function showView(v){[landingView,surveyView,thankView].forEach(x=>{x.hidden=x!==v;x.classList.toggle("active-view",x===v)});window.scrollTo({top:0,behavior:"smooth"})}
startSurveyBtn.addEventListener("click",()=>{renderQuestions();createCaptcha();showView(surveyView);history.pushState({view:"survey"},"",`${location.pathname}#survey`)})
window.addEventListener("popstate",()=>{const h=location.hash;if(h==="#survey"){renderQuestions();showView(surveyView)}else if(h==="#submitted")showView(thankView);else showView(landingView)})

function renderQuestions(){if(questionsContainer.dataset.rendered==="true")return;questionsContainer.dataset.rendered="true";questionsContainer.innerHTML='<div class="section-heading"><span class="section-number">1</span><div><h2>20 core financial-motivation questions</h2><p>Every question measures a defined concept from the six financial methods.</p></div></div>';QUESTIONS.forEach(q=>questionsContainer.appendChild(buildQuestion(q)));updateProgress()}
function buildQuestion(q){
 const w=document.createElement("article");w.className="question";w.dataset.qid=q.id;
 const head=document.createElement("div");head.className="question-head";head.innerHTML=`<div class="question-number">Q${String(q.id).padStart(2,"0")}</div><div><div class="question-title">${esc(q.title)} <span class="req">*</span></div>${q.note?`<div class="question-note">${esc(q.note)}</div>`:""}</div>`;w.appendChild(head);
 const control=document.createElement("div");control.className="question-control";
 if(q.type==="single"||q.type==="multi"){
   const list=document.createElement("div");list.className="option-list";
   q.options.forEach(opt=>{const lab=document.createElement("label");lab.className="option";const typ=q.type==="multi"?"checkbox":"radio",nm=q.type==="multi"?`q${q.id}[]`:`q${q.id}`;lab.innerHTML=`<input type="${typ}" name="${nm}" value="${escAttr(opt)}"><span>${esc(opt)}</span>`;list.appendChild(lab)});
   control.appendChild(list);list.addEventListener("change",()=>{if(q.other){const selected=[...list.querySelectorAll("input:checked")].map(x=>x.value);document.getElementById(`q${q.id}OtherBox`).classList.toggle("visible",selected.includes("Other financial allowance / benefit"))}clearQuestionError(q.id);updateProgress()});
   if(q.other){const box=document.createElement("div");box.id=`q${q.id}OtherBox`;box.className="other-field";box.innerHTML=`<input id="q${q.id}Other" type="text" placeholder="Specify the other financial benefit / allowance" maxlength="120"><div id="q${q.id}OtherError" class="error-text"></div>`;control.appendChild(box)}
 }
 if(q.type==="range"){
   control.innerHTML=`<div class="range-wrap"><div class="range-row"><span>Current response</span><span id="rangeValue${q.id}" class="range-value">${q.defaultValue}%</span></div><input id="q${q.id}" name="q${q.id}" type="range" min="${q.min}" max="${q.max}" step="${q.step}" value="${q.defaultValue}"><div class="range-minmax"><span>${esc(q.minLabel)}</span><span>${esc(q.maxLabel)}</span></div></div>`;
   const r=control.querySelector("input");r.addEventListener("input",()=>{document.getElementById(`rangeValue${q.id}`).textContent=`${r.value}%`;clearQuestionError(q.id);updateProgress()});
 }
 if(q.type==="metric7"){
   const grid=document.createElement("div");grid.className="metric-grid";q.options.forEach((opt,i)=>{const id=`q${q.id}_${i}`,item=document.createElement("div");item.className="metric-option";item.innerHTML=`<input id="${id}" name="q${q.id}" type="radio" value="${escAttr(opt)}"><label for="${id}">${esc(opt)}</label>`;grid.appendChild(item)});control.appendChild(grid);control.addEventListener("change",()=>{clearQuestionError(q.id);updateProgress()})
 }
 w.appendChild(control);const err=document.createElement("div");err.id=`q${q.id}Error`;err.className="error-text";w.appendChild(err);return w;
}
function updateProgress(){let answered=0;QUESTIONS.forEach(q=>{let ok=false;if(q.type==="multi")ok=document.querySelectorAll(`input[name="q${q.id}[]"]:checked`).length>0;else if(q.type==="range")ok=true;else ok=!!document.querySelector(`input[name="q${q.id}"]:checked`);if(ok)answered++});progressCount.textContent=answered;progressFill.style.width=`${Math.round(answered/20*100)}%`}
function createCaptcha(){captcha.a=Math.floor(Math.random()*8)+2;captcha.b=Math.floor(Math.random()*8)+1;captchaQuestion.textContent=`Verification: ${captcha.a} + ${captcha.b} = ?`;captchaAnswer.value="";clearSimpleError(captchaAnswer,"captchaError")}
newCaptchaBtn.addEventListener("click",createCaptcha);workplacePhoto.addEventListener("change",()=>clearSimpleError(workplacePhoto,"photoError"));
function collectAnswers(){const out={};QUESTIONS.forEach(q=>{if(q.type==="multi"){out[`q${q.id}`]=[...document.querySelectorAll(`input[name="q${q.id}[]"]:checked`)].map(x=>x.value);const o=document.getElementById(`q${q.id}Other`);out[`q${q.id}_other`]=o?o.value.trim():""}else if(q.type==="range")out[`q${q.id}`]=document.getElementById(`q${q.id}`).value;else{const s=document.querySelector(`input[name="q${q.id}"]:checked`);out[`q${q.id}`]=s?s.value:""}});return out}
function validateSurvey(){clearAllErrors();let first=null;const firstName=document.getElementById("firstName"),secondName=document.getElementById("secondName"),email=document.getElementById("email"),org=document.getElementById("organization"),dept=document.getElementById("department"),summary=document.getElementById("summary");
 if(!/^[A-Z][a-z]+(?:[ '-][A-Z][a-z]+)*$/.test(firstName.value.trim())){setFieldError(firstName,"firstNameError","Enter a first name with standard capitalization, e.g. Joyson.");first||=firstName}
 if(secondName.value.trim()&&!/^[A-Z][a-z]+(?:[ '-][A-Z][a-z]+)*$/.test(secondName.value.trim())){setFieldError(secondName,"secondNameError","Use standard capitalization, e.g. Rao.");first||=secondName}
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email.value.trim())){setFieldError(email,"emailError","Enter a valid email address.");first||=email}
 const generic=["ngo","organization","organisation","company","firm","business","office","institute"];if(!org.value.trim()){setFieldError(org,"organizationError","Enter the specific organisation or company name.");first||=org}else if(generic.includes(org.value.trim().toLowerCase())){setFieldError(org,"organizationError","Use the specific organisation name, e.g. Aakash Institute, not a generic label.");first||=org}
 if(dept.value.trim().length<2){setFieldError(dept,"departmentError","Enter the specific department, unit or role group.");first||=dept}
 QUESTIONS.forEach(q=>{if(q.type==="multi"){const s=document.querySelectorAll(`input[name="q${q.id}[]"]:checked`);if(!s.length){setQuestionError(q.id,"Select at least one applicable option.");first||=document.querySelector(`[data-qid="${q.id}"]`)}if(q.other&&[...s].some(x=>x.value==="Other financial allowance / benefit")){const o=document.getElementById(`q${q.id}Other`);if(!o.value.trim()){setFieldError(o,`q${q.id}OtherError`,"Please specify the other benefit you selected.");first||=o}}}else if(q.type==="range"){if(document.getElementById(`q${q.id}`).value===""){setQuestionError(q.id,"Move the slider to record your answer.");first||=document.getElementById(`q${q.id}`)}}else if(!document.querySelector(`input[name="q${q.id}"]:checked`)){setQuestionError(q.id,"Select one answer.");first||=document.querySelector(`[data-qid="${q.id}"]`)}})
 if(summary.value.length>1200){setFieldError(summary,"summaryError","Keep the summary within 1200 characters.");first||=summary}
 if(!captchaAnswer.value.trim()){setFieldError(captchaAnswer,"captchaError","Complete the verification calculation.");first||=captchaAnswer}else if(Number(captchaAnswer.value.trim())!==captcha.a+captcha.b){setFieldError(captchaAnswer,"captchaError","The verification answer is incorrect.");first||=captchaAnswer}
 if(!agreeTerms.checked){document.getElementById("agreeError").textContent="You must agree before submitting the survey.";first||=agreeTerms}
 if(first){first.scrollIntoView({behavior:"smooth",block:"center"});try{first.focus({preventScroll:true})}catch(_){}return false}return true}

surveyForm.addEventListener("submit",async e=>{e.preventDefault();submitStatus.className="submit-status";submitStatus.textContent="";if(!validateSurvey()){submitStatus.className="submit-status error";submitStatus.textContent="Please correct the fields marked in red.";return}submitBtn.disabled=true;submitBtn.textContent="Preparing submission…";overlay.classList.add("active");try{const photo=await preparePhoto();submitViaHiddenFrame(photo)}catch(err){overlay.classList.remove("active");submitBtn.disabled=false;submitBtn.textContent="Submit Survey";submitStatus.className="submit-status error";submitStatus.textContent=err.message||"The submission could not be prepared."}})
function preparePhoto(){const file=workplacePhoto.files&&workplacePhoto.files[0];if(!file)return Promise.resolve({data:"",name:""});if(!["image/jpeg","image/png","image/webp"].includes(file.type))return Promise.reject(new Error("Please choose a JPG, PNG or WebP image."));if(file.size>5*1024*1024)return Promise.reject(new Error("Please choose an image under 5 MB."));return fileToDataUrl(file).then(data=>compressImage(data,1200,.72)).then(compressed=>{const b64=compressed.split(",")[1]||"";if(b64.length>700000)throw new Error("The photo is still too large after compression. Please choose a smaller image.");return{data:b64,name:`${safeFile(file.name).replace(/\.[^.]+$/,'')}.jpg`}})}
function fileToDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(new Error("Could not read the selected image."));r.readAsDataURL(file)})}
function compressImage(data,maxSide,quality){return new Promise((res,rej)=>{const img=new Image();img.onload=()=>{const s=Math.min(1,maxSide/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(img.width*s));c.height=Math.max(1,Math.round(img.height*s));const ctx=c.getContext("2d",{alpha:false});ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",quality))};img.onerror=()=>rej(new Error("Could not decode the selected image."));img.src=data})}
function submitViaHiddenFrame(photo){const frame=document.createElement("iframe");frame.name=`submit_${Date.now()}`;frame.style.display="none";document.body.appendChild(frame);const form=document.createElement("form");form.method="POST";form.action=API_URL;form.target=frame.name;form.enctype="application/x-www-form-urlencoded";form.style.display="none";const a=collectAnswers(),values={form_type:"survey",firstName:document.getElementById("firstName").value.trim(),secondName:document.getElementById("secondName").value.trim(),email:document.getElementById("email").value.trim().toLowerCase(),organization:document.getElementById("organization").value.trim(),department:document.getElementById("department").value.trim(),summary:document.getElementById("summary").value.trim(),photo_data:photo.data,photo_name:photo.name,captcha_answer:String(captcha.a+captcha.b),captcha_expected:String(captcha.a+captcha.b),agree_terms:agreeTerms.checked?"yes":"no"};
 for(let i=1;i<=20;i++)values[`q${i}`]=Array.isArray(a[`q${i}`])?JSON.stringify(a[`q${i}`]):a[`q${i}`]||"";values.q1_other=a.q1_other||"";Object.entries(values).forEach(([k,v])=>{const input=document.createElement("input");input.type="hidden";input.name=k;input.value=v;form.appendChild(input)});
 const handler=event=>{if(!event.data||event.data.type!=="survey-result")return;window.removeEventListener("message",handler);frame.remove();form.remove();overlay.classList.remove("active");if(event.data.ok){document.getElementById("thankUserId").textContent=event.data.userId||"Recorded";document.getElementById("thankText").textContent=event.data.message||"Your response has been recorded successfully.";showView(thankView);history.pushState({view:"submitted"},"",`${location.pathname}#submitted`)}else{submitBtn.disabled=false;submitBtn.textContent="Submit Survey";submitStatus.className="submit-status error";submitStatus.textContent=event.data.message||"The submission could not be saved.";if(event.data.field)focusServerField(event.data.field,event.data.message);createCaptcha()}};window.addEventListener("message",handler);document.body.appendChild(form);form.submit()}
function focusServerField(field,message){const el=document.getElementById(field);if(el){const errorId=`${field}Error`;setFieldError(el,errorId,message);el.scrollIntoView({behavior:"smooth",block:"center"});try{el.focus({preventScroll:true})}catch(_){}return}if(field==="q1")setQuestionError(1,message)}
function clearAllErrors(){document.querySelectorAll(".field.invalid,.question.invalid,.captcha-box.invalid").forEach(x=>x.classList.remove("invalid"));document.querySelectorAll(".error-text").forEach(x=>x.textContent="");submitStatus.textContent="";submitStatus.className="submit-status"}
function setFieldError(field,id,message){const c=field.closest(".field")||field.closest(".captcha-box");if(c)c.classList.add("invalid");const e=document.getElementById(id);if(e)e.textContent=message}
function setQuestionError(id,message){const q=document.querySelector(`[data-qid="${id}"]`);if(q)q.classList.add("invalid");const e=document.getElementById(`q${id}Error`);if(e)e.textContent=message}
function clearQuestionError(id){const q=document.querySelector(`[data-qid="${id}"]`);if(q)q.classList.remove("invalid");const e=document.getElementById(`q${id}Error`);if(e)e.textContent=""}
function clearSimpleError(field,id){const c=field.closest(".field")||field.closest(".captcha-box");if(c)c.classList.remove("invalid");const e=document.getElementById(id);if(e)e.textContent=""}
function safeFile(s){return String(s).replace(/[^a-zA-Z0-9._-]+/g,"_").slice(0,100)||"workplace_photo"}
function esc(s){return String(s).replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[x]))}
function escAttr(s){return esc(s)}
